ajustes

diff --git a/s2i/bin/assemble b/s2i/bin/assemble
--- a/s2i/bin/assemble
+++ b/s2i/bin/assemble
@@ -9,36 +9,6 @@
 #
 #HOME directory of base image =>  /opt/app-root/src
 
-execute_maven_build()
-{
-  echo "---> Building application using Maven ..."
-
-  MAVEN_ARGS="package -DskipTests ${MAVEN_ARGS_APPEND}"
-  echo "---> Found pom.xml.  Attempting to build with 'mvn ${MAVEN_ARGS}'"
-
-  echo "---> Using $(mvn --version)"
-
-  # Execute the actual build
-  mvn -e $MAVEN_ARGS
-
-  ERR=$?
-  if [ $ERR -ne 0 ]; then
-    echo "Aborting due to error code $ERR from Maven build"
-    exit $ERR
-  fi
-
-  # Copy built artifacts (if any!) from the target/ directory
-  # to the $DEPLOY_DIR directory for later deployment
-  cp -v $HOME/target/*.* $DEPLOY_DIR 2> /dev/null
-
-  # Clean up after Maven run ....
-  mvn clean
-
-  if [ -d "$HOME/.m2/repository" ]; then
-    rm -rf $HOME/.m2/repository
-  fi
-}
-
 execute_gradle_build()
 {
   echo "---> Building application using Gradle ..."
@@ -94,21 +64,20 @@ cp -Rf /tmp/src/. ./
 echo "---> Copied application source to $HOME ..."
 ls -la $HOME
 
-echo "---> S2I:assemble Build type=$BUILD_TYPE ..."
-if [ $BUILD_TYPE = "Maven" ] && [ -f "$HOME/pom.xml" ]; then
-  execute_maven_build
-elif [ $BUILD_TYPE = "Gradle" ] && [ -f "$HOME/build.gradle" ]; then
-  execute_gradle_build
-else
-  # Copy the fat jar to the deployment directory
-  cp -v $HOME/*.jar $DEPLOY_DIR 2> /dev/null
-fi
+echo "---> S2I:assemble Build type=Gradle"
+execute_gradle_build
 
-# For Spring Boot, there should only be 1 fat jar
+
+# For Spring Boot, there should only be 1 fat jar/war
+
 if [ $(ls $DEPLOY_DIR/*.jar | wc -l) -eq 1 ]; then
   mv $DEPLOY_DIR/*.jar $DEPLOY_DIR/app.jar
   [ ! -f $DEPLOY_DIR/app.jar ] && echo "Application could not be properly built." && exit 1 
   echo "---> Application deployed successfully.  jar file is located in $DEPLOY_DIR/app.jar"
+elif [ $(ls $DEPLOY_DIR/*.war | wc -l) -eq 1 ]; then
+  mv $DEPLOY_DIR/*.war $DEPLOY_DIR/app.war
+  [ ! -f $DEPLOY_DIR/app.war ] && echo "Application could not be properly built." && exit 1 
+  echo "---> Application deployed successfully.  war file is located in $DEPLOY_DIR/app.war"
 else
   exit 1
 fi
